# Generated by Django 5.1.7 on 2025-03-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
